### PR TITLE
Update v3.13.0

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #2
Closes #3
Closes #4
Closes #5

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Hi @synapticarbors, this PR updates the recipe to the newest version and adds me as a maintainer, hope that's alright.

**Comment by synapticarbors** [comment]
@BastianZim -- Thanks for taking care of this and apologies for neglecting this feedstock.

**Comment by BastianZim** [comment]
No worries, my pleasure!

**Pull request merged**
